Improve error handling when publishing the metadata
planetary-social/nos pull request #1052
Opened 2024-04-17 12:51 UTC by martindsq

#984 

We cannot prevent publishing metadata (we do this when updating the profile, registering a nos.social username, deleting the username, etc) from failing because it could fail if the user doesn't have connectivity for example. But we can improve error handling so that any code that uses the `publishMetadata()` has a chance to react to a failure in that step.

I marked it as `throws` and, in case of registering/deleting NIP-05 usernames, revert the action. Even though that metadata could be published later (not automatically, just if the users updates the profile again, so we can consider about adding a code that knows if there are unpublished changes in the metadata and publish them, but I think this is not important), we cannot let the user continue as if the NIP-05 change was published correctly.

2024-04-18 14:33 UTC, joshuatbrown requested changes
This is great! Glad we're improving our error handling.

2024-04-18 14:33 UTC, joshuatbrown commented on Nos/Service/CurrentUser.swift
> +    @MainActor func publishMetaData() async throws {
```suggestion
    @MainActor func publishMetadata() async throws {
```

Metadata is one word, so let's spell it this way here and throughout. We do sometimes but haven't been consistent, so I'm hoping we can make progress in that direction.

2024-04-18 14:33 UTC, joshuatbrown commented on Nos/Views/ProfileEdit/CreateUsernameWizard/ExternalNIP05/NiceWorkSheet.swift
I noticed we don't use namesAPI to register here like we do in ExcellentChoiceSheet. What's the reason for that?

2024-04-18 14:33 UTC, joshuatbrown commented on Nos/Views/ProfileEdit/ProfileEditView.swift
> +            Log.debug("Error while publishing to relays")
Do we think a retry here might work?

2024-04-24 22:56 UTC, martindsq commented on Nos/Views/ProfileEdit/CreateUsernameWizard/ExternalNIP05/NiceWorkSheet.swift
In `ExcellentChoiceSheet` we use `NamesAPI` to ask our server to add my `npub` to the JSON file as the username I chose.  On the other hand, `NiceWorkSheet` doesn't need to do that because the user already did that in the third-party server he is using. For example, by that time, I already updated the JSON file at martin.dutra.uy with my `npub`.

In this case, we only need to publish a `kind: 0` event with the profile update.

2024-04-24 22:57 UTC, martindsq commented on Nos/Views/ProfileEdit/ProfileEditView.swift
> +            Log.debug("Error while publishing to relays")
Yes, It's a good idea.

2024-04-25 13:10 UTC, joshuatbrown approved these changes
Great work!

2024-04-25 13:53 UTC, merged