Send to nos account moderation
planetary-social/nos pull request #1235
Opened 2024-06-13 14:37 UTC by dcadenas

## Issues covered
Covers https://github.com/planetary-social/nos/issues/1083, https://github.com/planetary-social/nos/issues/1093, https://github.com/planetary-social/cleanstr/issues/44, https://github.com/planetary-social/nos/issues/1084
## Description

It adds a `Send To Nos` option in the account menu similar to the note version so that users can have flag anonymously

## How to test
1. Navigate to some user's menu
2. Select Flag this User
3. Select a category
4. Select `Send to Nos`
5. Confirm Dialog
6. Verify report in Slack channel

2024-06-14 20:01 UTC, mplorentz requested changes
I tested all the reporting flows: public note, anonymous note, public author, anonymous author. All look good to me! Nice work!

However there were some configuration changes we'll need to revert before merging.

2024-06-14 20:27 UTC, dcadenas commented on Nos.xcodeproj/project.pbxproj
> +				"DEVELOPMENT_TEAM[sdk=iphoneos*]" = FU5BU675QQ;
I think I was trying to run the app in the real phone and I was using my ID but I don't really know how to and my account is not up to date. Not a big deal really, I don't need it

2024-06-18 13:59 UTC, mplorentz approved these changes
Ready to merge!

2024-06-18 14:07 UTC, joshuatbrown commented
I'll merge since I think Daniel is still out and I'm working on a related ticket.

2024-06-18 14:18 UTC, merged