Turn off automatic scren captures in PostHog
planetary-social/nos pull request #1383
Opened 2024-08-06 19:40 UTC by martindsq

## Issues covered
None

## Description
This PR disables the automatic screen event capture in PostHog, as it isn’t useful for Swift, and clutters PostHog with unnecessary events.
Relevant discussion https://planetary-app.slack.com/archives/C04PLR5QFQQ/p1722972656748709 

## How to test
1. Use the app
2. Open PostHog
3. See that is not cluttered anymore

## Screenshots/Video
![Captura de pantalla 2024-08-06 a la(s) 4 28 21 p  m](https://github.com/user-attachments/assets/1757d7f1-cf08-4da4-bf43-37183060593a)

2024-08-07 13:45 UTC, joshuatbrown requested changes
This looks good and works for me. The only change I'm requesting here is that we create a ticket and include it in the PR description. This will make it easier to track what we've done and flag it for Linda as a change we made, even if it's not easy for her to test. I suppose I'd also love a CHANGELOG entry since this seems like a significant change to our reporting.

2024-08-07 18:33 UTC, martindsq commented
@joshuatbrown thanks for the review. I addressed your comments.

2024-08-08 14:24 UTC, joshuatbrown requested changes
One more suggestion for the CHANGELOG entry, then we're good. Thanks!

2024-08-08 14:24 UTC, joshuatbrown commented on CHANGELOG.md
> +- Removed analytics events sent each time the user navigate to a new screen.
```suggestion
- Disabled automatically generated analytics events that were sent each time the user navigated to a new screen.
```

2024-08-08 19:39 UTC, joshuatbrown approved these changes
Perfect!

2024-08-08 19:47 UTC, merged