Replace remaining Color(hex:) references with semantic Color assets
planetary-social/nos pull request #1403
Opened 2024-08-15 13:27 UTC by lingoslinger

## Issues covered
[1375](https://github.com/planetary-social/nos/issues/1375) (ongoing work)

## Description
Replaced remaining Color(hex:) references with semantically names colors in Colors.xcassets

## How to test
- Verify that the hex colors in each asset match the hard coded hex color in the changed file; smoke test the app to verify

## Notes
- changes to Color(white: opacity) and hard coded RGB colors will be addressed in separate PRs.

2024-08-15 17:38 UTC, martindsq approved these changes

2024-08-16 13:28 UTC, joshuatbrown requested changes
One color isn't the same, so let's fix that and get this merged! Thanks again, @lingoslinger!

2024-08-16 13:28 UTC, joshuatbrown commented on Nos/Assets/Colors.xcassets/big-action-button-gradient-bottom.colorset/Contents.json
> +          "green" : "0x43",
```suggestion
          "green" : "0x4E",
```

2024-08-16 14:02 UTC, joshuatbrown approved these changes
Great work!

2024-08-16 14:11 UTC, merged