Display images with new image viewer
planetary-social/nos pull request #1407
Opened 2024-08-16 14:59 UTC by joshuatbrown

## Issues covered
#1164 

## Description
Displays full-screen images with the new image viewer. The gallery view will be covered in #1177.

## How to test
1. Navigate to a post with an image
2. Tap on it
3. You're in the new image viewer!
4. Double-tap to zoom in
5. Drag around to pan
6. Double-tap again to zoom out
7. Swipe down or tap the `x` to dismiss

## Screenshots/Video
Coming soon!

2024-08-16 19:10 UTC, martindsq requested changes

2024-08-16 19:10 UTC, martindsq commented on Nos/Views/LinkPreview.swift
> +        Button(
Given that Button is a well-known component in SwiftUI, I prefer the more succinct declaration:

```
Button {
    isViewerPresented 0 true
} label: {
    WebImage()
}
```

2024-08-16 19:10 UTC, martindsq commented on Nos/Views/LinkPreview.swift
> +        Button(
Given that Button is a well-known component in SwiftUI, I prefer the more succinct declaration:

```
Button {
    isViewerPresented 0 true
} label: {
    ....
}
```

2024-08-16 19:10 UTC, martindsq commented on Nos/Views/LinkPreview.swift
> +    @State private var isViewerPresented: Bool = false
You can get rid of `: Bool` given that it is already implicit in `= false`

2024-08-16 19:10 UTC, martindsq commented on Nos/Views/Components/Images/ImageViewer.swift
> +                Button(
Given that Button is a well-known component in SwiftUI, I prefer the more succinct declaration:

```
Button {
    dismiss()
} label: {
    ....
}
```

2024-08-16 20:27 UTC, joshuatbrown commented on Nos/Views/Components/Images/ImageViewer.swift
> +                                        height: lastOffset.height + value.translation.height * 1.5
@martindsq you said this feels weird, like the image is moving too much. We can adjust these values and see how it works for you:

```suggestion
                                        width: lastOffset.width + value.translation.width,
                                        height: lastOffset.height + value.translation.height
```

2024-08-19 19:00 UTC, joshuatbrown commented
We're moving forward with #1413.

2024-08-19 19:00 UTC, closed without merging