add localized quotation marks on Notifications view #1422
planetary-social/nos pull request #1424
Opened 2024-08-24 12:36 UTC by bryanmontz

## Issues covered
Closes #1422 

## Description
This change localizes the quotation marks added around content in notes referenced on the Notifications view. It is implemented as a String extension that could be applied anywhere.

## How to test
1. Navigate to Notifications view.
2. Observe quotation marks around content.

## Screenshots
English:  
| Before | After |
| --- | --- |
|<img width="340" alt="before" src="https://github.com/user-attachments/assets/1ecb94da-6024-4ddc-98d5-180b65163305">|<img width="340" alt="after" src="https://github.com/user-attachments/assets/f0a4b2c9-d4de-4147-86f6-4c8509aa2faf">|

French:  
<img width="340" alt="french" src="https://github.com/user-attachments/assets/297871ec-d6ba-45ab-b54c-45683511eee3">

Japanese:  
<img width="415" alt="japanese" src="https://github.com/user-attachments/assets/74ca55f0-418a-49c6-a721-1ddfa7140ffa">

2024-08-26 13:34 UTC, joshuatbrown commented
@bryanmontz Would you mind updating the PR description to remove "Closes #1422"? That wording breaks our process when the PR is merged since it closes the issue and moves it to Done, skipping our UAT and QA steps.

2024-08-26 13:36 UTC, bryanmontz commented
> @bryanmontz Would you mind updating the PR description to remove "Closes #1422"? That wording breaks our process when the PR is merged since it closes the issue and moves it to Done, skipping our UAT and QA steps. If you just remove the word "Closes", everything in our process still works.

Done! Sorry about that.

2024-08-26 13:56 UTC, joshuatbrown requested changes
Code looks good. I did find an issue: when a link is at the beginning or end, the quote mark appears as part of the link. I'd expect the quote mark to always be white.

<img width="235" alt="Screenshot 2024-08-26 at 9 55 21 AM" src="https://github.com/user-attachments/assets/830530f9-0b4d-4775-b9d2-8309c4610b24">

2024-08-27 12:40 UTC, bryanmontz commented
Thanks for finding that! Fixed this issue. The only thing is that if `NoteParser` ever adds style attributes, we'll need them here as well. Right now it doesn't seem to.

2024-08-27 15:52 UTC, joshuatbrown approved these changes
Looks great, and works perfectly!

2024-08-27 15:52 UTC, joshuatbrown commented on CHANGELOG.md
> +- Localized the quotation marks on the Notifications view.
I think I'd like to have these sorted, so the ones that go in the release notes are above all the ones that say `[skip-release-notes]`. Would it make more sense to just have a section like `### Internal` under `## [Unreleased]`, and then it's implied that the Internal ones are skipped? Or two sections: `### External` and `### Internal`? Or maybe even better names than those -- I'm just not coming up with anything else right now.

This is just an idea; I don't think we need to do it right now unless we settle on a good approach, but I wanted to start talking about it.

2024-08-27 15:59 UTC, merged