Replace GIFs with new GIF viewer
planetary-social/nos pull request #1437
Opened 2024-08-28 19:40 UTC by joshuatbrown

## Issues covered
#1168 

## Description
Like it says in the title. GIFs now appear in the feed, profile, and thread with a "GIF" button on top of them. 

## How to test
1. Navigate to Settings
2. Toggle Enable new media display to "On"
3. Find or post a GIF (here's a note with one: note1nvf6wm257sku94zt9dqaw439a67dg6qq8wwjh9xg2pny07rpvk8qp8xkcq)
4. Tap anywhere on the GIF to play the animation
5. Tap a GIF that's animating to view the GIF full screen
6. Double-tap to zoom in the full-screen viewer
7. Double-tap to zoom out
8. Tap the "X" button or swipe down to close the image viewer

## Screenshots/Video
https://github.com/user-attachments/assets/37e44ea1-af2b-4989-9bb6-1f3a0cddeed9

2024-08-28 19:43 UTC, joshuatbrown commented on Nos.xcodeproj/project.pbxproj
> +				branch = bugfix/webimage_isAnimating_binding;
We'll definitely want to update this before merging the PR. But I thought there's a chance they might get the [SDWebImageUI PR](https://github.com/SDWebImage/SDWebImageSwiftUI/pull/333) merged and released before _this_ PR is reviewed and ready to merge. Either way, I'll set this to a released version of SDWebImageSwiftUI before merging -- the only question is whether I'll have to use a workaround in our code or not.

2024-08-29 14:59 UTC, joshuatbrown commented on Nos.xcodeproj/project.pbxproj
> +				branch = bugfix/webimage_isAnimating_binding;
Updated -- we're on release 3.1.2 now!

2024-08-29 15:26 UTC, mplorentz requested changes
This code is so clean, I love it. I did find some weirdness when rotating gifs. See the two below cases:

- I expect this gif to fill the screen vertically when in landscape, but there is a gap at the bottom: `note1gwug9ke6x40uk8qku0fy0eszr7jldfwj4ap6meqzqhcr3jvyg7kswym5zs` 

https://github.com/user-attachments/assets/715fd4cd-68db-4cac-b676-99aab06034f5

- This gif has a weird gap in portrait after I pinch to zoom a bit in landscape: `note19h0x9um6ymwnmmnjqnc6mvmfpcnqq0t0qmam009fwdlwnzlmrqgq76aptp` 

https://github.com/user-attachments/assets/b80e2b45-fc64-4c0c-bc46-261bf313f6b0

2024-08-29 15:54 UTC, joshuatbrown commented on CHANGELOG.md
> +- Added an overlay to GIFs that plays the animation when tapped. Currently behind the “Enable new media display” feature flag. [skip-release-notes]
That's the idea. Right now it's 100% manual; maybe in the future it'll be 100% automated. And maybe #1438 will change the approach slightly.

2024-08-29 17:25 UTC, joshuatbrown commented
> This code is so clean, I love it. I did find some weirdness when rotating gifs. See the two below cases:
> 
> * I expect this gif to fill the screen vertically when in landscape, but there is a gap at the bottom: `note1gwug9ke6x40uk8qku0fy0eszr7jldfwj4ap6meqzqhcr3jvyg7kswym5zs`
> 
> * This gif has a weird gap in portrait after I pinch to zoom a bit in landscape: `note19h0x9um6ymwnmmnjqnc6mvmfpcnqq0t0qmam009fwdlwnzlmrqgq76aptp`
 
Unfortunately I think these are general issues with our ImageViewer; the same weird things happen for me when rotating plain old images: `note1qdsj4qdn6vy5sfmpn93wp4tpx6czggcrthckagz33mdkja8a68pqd0mjsg`

I'll look and see what I can do.

2024-08-29 17:37 UTC, mplorentz commented
@joshuatbrown 
> Unfortunately I think these are general issues with our ImageViewer; the same weird things happen for me when rotating plain old images: `note1qdsj4qdn6vy5sfmpn93wp4tpx6czggcrthckagz33mdkja8a68pqd0mjsg`
> 
> I'll look and see what I can do.

In that case I approve and we can address that in another PR.

2024-08-29 17:37 UTC, mplorentz approved these changes

2024-08-29 18:57 UTC, joshuatbrown commented
> > Unfortunately I think these are general issues with our ImageViewer; the same weird things happen for me when rotating plain old images: `note1qdsj4qdn6vy5sfmpn93wp4tpx6czggcrthckagz33mdkja8a68pqd0mjsg`
> > I'll look and see what I can do.
> 
> In that case I approve and we can address that in another PR.

Yeah, I ended up debugging a bit and documenting my findings in a Notion doc. I'll create a ticket, add my notes to it, and we can address it when it's prioritized.

2024-08-29 19:00 UTC, joshuatbrown commented
New ticket to address issues: https://github.com/planetary-social/nos/issues/1440

2024-08-29 19:06 UTC, merged