performance improvements for AuthorLabel #1458
planetary-social/nos pull request #1590
Opened 2024-10-06 13:35 UTC by bryanmontz

## Issues covered
#1458 

## Description
This is a small step in improving the scroll performance of the app and is meant to be a pattern check for other devs. If these changes are acceptable, then we could implement similar changes widely.

My goal here was to identify and address one small performance issue. Here is the profiling scenario to repeat between changes:

## How to test
1. While signed in to the app build it for profiling by click-and-hold-ing on the Play button and dragging to select Profile.
2. When Instruments opens, select the SwiftUI instrument.
3. Click the red record button to begin profiling.
4. Once the app settles on the feed, do two strong flings to move down the feed.
5. Stop the recording.
6. Click and drag left to right to select the area of time during the two flings.
7. Select the "View body" instrument, and observe the results.
The "View body" instrument gives you the count and duration of SwiftUI view body methods for all the views in the app. If you sort the results by "Total Duration", you'll see the "worst performance offenders".

Here's how the ranking looks before the changes in this PR:
![before_changes](https://github.com/user-attachments/assets/88a91bb2-11d8-4844-8aa2-225331ebad4b)
Here you see that `AuthorLabel` was drawn 29 times for a total of 33.32ms. This is miserable performance. At 60Hz, a single frame *must* take less than 16.67ms overall, so we want individual views' times to be MUCH less than that.

After only removing the xcstringstool usage in `AuthorLabel` let's run the same test again:
![after string change](https://github.com/user-attachments/assets/af0d6fcf-e6a9-466d-9e70-aa430173f603)
This time you see around the same number of redraws, but each one takes 1/10th the time! This is a lot better, but we're still adding up to milliseconds here, and we'd prefer to get it lower.

The next big performance improvement is to cache the result of the `attributedAuthor` method, which is taking too long, in a view-scoped cache. I also made another change to pass only the relevant properties of `Author` to this view, rather than the entire object. This is good practice regardless of performance.
![after all changes](https://github.com/user-attachments/assets/118d098c-4ccc-445e-8b67-1898c611241b)
Now we see the performance we want to get from this view. Even with 22 redraws, the total time is on the order of hundreds of microseconds.

2024-10-08 14:35 UTC, joshuatbrown commented
👀

2024-10-08 14:59 UTC, joshuatbrown approved these changes
This looks good to me -- both the code and the results I saw in Instruments. Since it's such an important change, I'd like to have @mplorentz review as well.

2024-10-09 17:56 UTC, mplorentz requested changes
Unfortunately it looks to me like this breaks the observation of the `author` by these views and makes them static. If you delete the app and launch it again with an empty Core Data database none of the names load on the home feed note cards.

I am hopeful we can get observation back without losing the performance improvements though. I think if we go back to using `@ObservedObject var author` (or maybe better: `@Bindable var author` to use `@Observable`) we can still set the cache up so that it only recomputes the `AttributedString` when the relevant properties on the author change and bust the cache when they do.

I think one way to approach it is to store the attributed string in an `@State var` and recompute it using `onChange(of: author)`. This will get recomputed too often, but not every time `body` is called, only when `author` changes (and only the properties on author I think, not when core data relationships are updated).

A more advanced approach might be to pass the whole `author` into the `Cache` and wrap the `attributedAuthor` creation in a [`withObservationTracking`](https://developer.apple.com/documentation/observation/withobservationtracking(_:onchange:)) block. Then the cache will only recompute the string when the one of the relevant stored properties on author changes (e.g. `displayName`, `name`, `hexadecimalPublicKey`, etc.

2024-10-23 12:54 UTC, bryanmontz commented
Thanks for pointing out that issue, @mplorentz. I have now tried a few different patterns and have not had success yet. I don't think we need @Bindable here because we don't need a two-way connection; we only need observation. I tried using `@ObservedObject var author` with `onChange(of: author)` and `onChange(of: author.safeName)`and that never seemed to fire the closure. I'm going to close this PR for now because I don't have a clear way forward, but I want to revisit performant patterns in the future.

2024-10-23 12:54 UTC, closed without merging