Open links in an in-app browser instead of safari
planetary-social/nos pull request #297
Opened 2023-05-02 17:08 UTC by mplorentz

kind of related to #294 - I'm just trying to make the thread view a better experience

2023-05-02 18:30 UTC, martindsq requested changes

2023-05-02 18:30 UTC, martindsq commented on Nos/Views/RelayView.swift
> +                        try! viewContext.save()
Shouldn't force try this database save operation and should show the error in an alert instead

2023-05-02 18:30 UTC, martindsq commented on Nos.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 16.0;
I did notice that the deployment target was 16.2 which seemed too recent for me, but I didn't know if it was intended or not. This kind of changes should be done in a distinct PR so can I know for sure if there are intended to be merged or not. The same for macos deployment target.

2023-05-02 18:35 UTC, martindsq commented on .xcode-version
> +14.3
This should be also in a distinct PR

2023-05-08 18:40 UTC, mplorentz commented
@martindsq sorry I think I had the wrong target branch on this. The diff is cleaner now.

2023-05-09 18:02 UTC, martindsq approved these changes

2023-05-09 18:02 UTC, martindsq commented
It's nice now!

2023-05-10 13:37 UTC, merged