Increased the size of the NoteOptionsButton
planetary-social/nos pull request #311
Opened 2023-05-02 21:40 UTC by mplorentz

Closes #287

2023-05-02 21:50 UTC, mplorentz commented
looks like the timestamps are now way offset from the ellipsis button on the iPhone. I'll fix that tomorrow.

2023-05-09 18:08 UTC, martindsq requested changes

2023-05-09 18:08 UTC, martindsq commented on Nos/Views/NoteOptionsButton.swift
> +                VStack {
There shouldn't be a need to add a VStack here. Just adding `.frame(minWidth: 44, minHeight: 44)` to `Image` seems to do the work in my tests.

2023-05-16 18:40 UTC, martindsq approved these changes

2023-05-18 18:19 UTC, merged