Improve thread display to make replies and root messages easier to see
planetary-social/nos pull request #597
Opened 2023-10-16 03:22 UTC by rabble

![Screenshot 2023-10-16 at 4 22 05 PM](https://github.com/planetary-social/nos/assets/76/34fee2c9-5036-475a-8349-a328f8dd25ce)
![Screenshot 2023-10-16 at 4 22 14 PM](https://github.com/planetary-social/nos/assets/76/b814c399-63ed-4365-b38d-b52f288cb904)

2023-10-18 22:16 UTC, mplorentz requested changes
I tried to test this but it won't build for me locally. Looks like there are some CI errors and merge conflicts to be fixed as well.

2023-10-25 17:46 UTC, mplorentz approved these changes
Working through some layout bugs on this branch. Might revert some things if I can't get them working in a reasonable amount of time so I can get the rest merged. 
![Screenshot 2023-10-25 at 1 45 41 PM](https://github.com/planetary-social/nos/assets/1165004/40f0da55-ff19-4fb0-aed7-8ed18efd9606)
![simulator_screenshot_5DACF996-E23A-4B0D-8A63-24059C27AB4C](https://github.com/planetary-social/nos/assets/1165004/cdeae370-e577-49b4-ac0f-aa49b9d8cc0e)

2023-10-25 19:24 UTC, mplorentz commented
I keep finding so many little layout bugs, and they aren't all fixed but I pushed some code that I think is better. @martindsq could you give this a review and say whether it's good enough to ship?

2023-10-26 17:37 UTC, martindsq approved these changes

2023-10-26 18:42 UTC, merged