adding the name of the person who was reported to the message
planetary-social/nos pull request #774
Opened 2024-01-03 07:29 UTC by rabble

I was getting really frustrated with user reports and not knowing WHO the report was of... It caused me to tap on show anyway button. This fixes it. 

![Screenshot 2024-01-03 at 8 28 28 PM](https://github.com/planetary-social/nos/assets/76/0dfc4829-1c6d-4f00-9ca6-ecd2be91e7fe)

2024-01-03 20:46 UTC, martindsq requested changes

2024-01-03 20:46 UTC, martindsq commented on Nos/Views/WarningView.swift
> +a
There is an extra "a" here that breaks the code

2024-01-03 20:46 UTC, martindsq commented on Nos/Assets/Localization/Localizable.xcstrings
> +            "value" : "**%2$@** publiqué un reportaje sobre **%1$@** por %3$@."
I recommend simply:

`**%2$@** reportó a **%1$@** por %3$@.`

2024-01-18 21:52 UTC, mplorentz commented
Closing for now since this has been stale for two weeks. Feel free to reopen after feedback is addressed.

2024-01-18 21:52 UTC, closed without merging