Fix bad data in the contact list
planetary-social/nos pull request #856
Opened 2024-01-24 22:48 UTC by mplorentz

This should fix #845. A description of the bug is in the comments on the ticket. The fix was to validate that `Author` keys are valid hexadecimal public keys before sending them to relays. I also added validation before writing Follows to the database. 

Writing the validation logic led me down a path of refactoring. I started adding an `isValid` property to `HexadecimalString`, but I realized that we weren't just validating that the string was hexadecimal, but also of the length we expect for a Nostr identifier. So I renamed `HexadecimalString` to `RawNostrID`. Then just for fun I typealiased `RawNostrID` into `RawEventID` and `RawAuthorID`. These types aren't strict (you can instantiate an invalid one) but it does help us communicate in our APIs what type of ID we expect. They also play nicely with Core Data. Maybe someday we should refactor these into a stronger type but I didn't want/need to do it now. 

I also added an analytics event to log "bad req:" errors from relays. This sort of message isn't standard in the protocol but several relays were sending it and that's how I eventually found this bug. This will help us see if there are other bugs like this in the wild.

2024-01-25 00:51 UTC, rabble commented
I tested this with a build on my phone with the bad follow data and for me this PR fixes my problems!

2024-01-25 17:32 UTC, joshuatbrown requested changes
I ran the app and it works for me, but I was never able to reproduce the issue.

2024-01-25 17:36 UTC, martindsq approved these changes
It's working fine for me

2024-01-25 22:06 UTC, mplorentz commented
@joshuatbrown could you address the remaining feedback here and get this merged? I'm assigning the ticket to you.

2024-01-26 16:54 UTC, joshuatbrown commented on Nos/Models/CoreData/Follow+CoreDataClass.swift
> +    // swiftlint:disable:next function_body_length
For now, let's just let it slide.

2024-01-26 17:03 UTC, joshuatbrown approved these changes

2024-01-26 17:53 UTC, merged