Fix URL detection of raw domain names
planetary-social/nos pull request #889
Opened 2024-02-15 21:37 UTC by joshuatbrown

Fixes URL detection of raw domain names (like nos.social, or www.nos.social, or anything without `http` or `https`).

Steps to test:

1. Create a new note with a URL that doesn't have `http` at the beginning
2. Post it
3. Observe that the link is formatted properly

2024-02-19 21:18 UTC, martindsq requested changes
It looks great. The only test I made that failed was

test:`\nnostr1.com`
expected: `\n[nostr1.com](https://nostr1.com)`
result: `[nostr1.com](https://nostr1.com)`

extractURLs fails with that but findAndReplaceUnformattedLinks doesn't.

I'm willing to accept this PR if fixing that edge case is problematic, I know it is a really edge case, but I'd like to see what you think though. Everything else look nice and I appreciate all the tests you wrote.

2024-02-21 22:27 UTC, joshuatbrown commented
@martindsq thanks for catching that. I think it's probably something we do want to address, so I'll look at it when I have some time.

2024-02-22 19:02 UTC, joshuatbrown commented
@martindsq I found out why -- `extractURLs` strips leading and trailing whitespace from strings, and that includes `\n`. I'm thinking we don't want to change that behavior since other code probably depends on it, so maybe we just leave this for now. Sound OK to you?

2024-02-22 19:08 UTC, martindsq approved these changes

2024-02-22 19:20 UTC, merged