Show the create name sheet after 5 secs
planetary-social/nos pull request #917
Opened 2024-02-29 21:07 UTC by martindsq

#803 

It presents the NIP-05 sheet from anywhere in the app 5 seconds after the user opens the app if it didn't set the nip-05 before

2024-03-07 18:56 UTC, martindsq commented
@joshuatbrown replaced the 5 sec delay with half a second

2024-03-08 14:18 UTC, joshuatbrown commented
@martindsq that seems much better to me. Would you update the PR title and description to match?

2024-03-08 14:57 UTC, joshuatbrown requested changes
Some comments and questions.

2024-03-08 17:32 UTC, joshuatbrown commented on CHANGELOG.md
> +- Parse links and mentions in Profile's about (or bios)
Oh I see now that we're intending to skip changelog which is fine with me. Just want to make sure this line isn't duplicated, then.

2024-03-12 17:32 UTC, martindsq commented
@joshuatbrown I included some lines that I used for debugging or demoing the feature. I apologize by this.

I fixed that and restored the CHANGELOG file from main

2024-03-13 21:29 UTC, joshuatbrown requested changes
Looks good overall; a few implementation suggestions.

2024-03-13 21:29 UTC, joshuatbrown commented on CHANGELOG.md
Looks like we'll want to sync with `main` again -- I'm seeing a deleted line here.

2024-03-13 21:29 UTC, joshuatbrown commented on Nos/Views/AppView.swift
> +        var shouldShowSheet: Bool
```suggestion
        let shouldShowSheet: Bool
```

2024-03-13 21:29 UTC, joshuatbrown commented on Nos/Views/AppView.swift
> +        let didPresentSheetInPast = UserDefaults.standard.string(forKey: key)
Maybe something like this is a little more clear for me:
```suggestion
        let didPresentSheetForNpub = UserDefaults.standard.string(forKey: key)
```

2024-03-13 21:29 UTC, joshuatbrown commented on Nos/Views/AppView.swift
> +        let key = "AppView_presentedNIP05SheetFor"
I don't know how much it matters that `AppView` presented it, so I might suggest a couple tweaks:
```suggestion
        let key = "didPresentNIP05SheetForNpub"
```

2024-03-13 21:29 UTC, joshuatbrown commented on Nos/Views/AppView.swift
> +            UserDefaults.standard.setValue(npub, forKey: key)
Do we generally just use `UserDefaults.standard` directly like this? It's sort of a hidden dependency; at least, hidden outside of this func. Do we have a way to specify it as a `@Dependency`? I still don't fully know how all of that works.

2024-03-14 18:20 UTC, martindsq commented
@joshuatbrown It's ready to be re-reviewed!

2024-03-14 19:48 UTC, joshuatbrown approved these changes
Great work!

2024-03-14 20:23 UTC, merged